
camunda.bpm:
    admin-user:
        id: kermit
        password: superSecret
        firstName: Kermit
    filter:
        create: All tasks

# CamundaBpmConfiguration -> CreateAdminUserConfiguration

logging:
    level:
        org.glassfish.jersey.servlet.WebComponent: ERROR
